frilance/FAQ/urls.py
from django.urls import path
from FAQ import views

app_name = "FAQ"
urlpatterns = [
    path('', views.FAQ, name = "FAQ")
]

frilance/frilance/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path ('settings/', include('settings.urls')),
    path ("profile/", include('user_profile.urls')),
    path("transactions/", include('transactions.urls')),
    path ("faq/", include("FAQ.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frilance/settings/urls.py
from django.urls import path
from settings import views

app_name = "settings"

urlpatterns = [
    path("", views.settings, name = 'settings'),
    path('settings/profile_update/', views.profile_update, name='profile_update'),
    path('settings/change_password/', views.change_password, name='change_password'),

]

frilance/settings/models.py
from django.db import models

# Create your models here.

frilance/settings/views.py
from urllib import request
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
import os
from django.conf import settings as django_settings

@login_required
def settings(request):
    return render(request, 'settings/setting.html')

@login_required
def profile_update(request):
    if request.method == 'POST':
        username = request.POST.get('profile-name')

        email = request.POST.get('profile-email')\

        image = request.FILES.get('profile-image')

        if username:
            request.user.username = username

        if email:
            request.user.email = email

        if image:
            old_image_path = None

            if request.user.account.image and os.path.isfile(os.path.join(django_settings.MEDIA_ROOT, request.user.account.image.path)):
                old_image_path = os.path.join(django_settings.MEDIA_ROOT, request.user.account.image.path)

            request.user.account.image = image
            request.user.account.save()

            if old_image_path:
                os.remove(old_image_path)

        request.user.save()
        messages.success(request, 'Профиль успешно обновлен!')
        return redirect('settings:settings') 

    return render(request,'settings/setting.html')

@login_required()
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Ваш пароль был успешно обновлен!')
            return redirect('settings:settings')
        else:
            messages.error(request, 'Пожалуйста, исправьте ошибку.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'settings/setting.html', {
        'form': form
    })

frilance/settings/templates/settings/setting.html

{% extends "main/base/base.html" %}
{% load static %}

{% block content %}
<main class="main-wrapper col-md-9 ms-sm-auto py-4 col-lg-9 px-md-4 border-start">
    <div class="title-group mb-3">
        <h1 class="h2 mb-0">Settings</h1>
    </div>
    
    <div class="row my-4">
        <div class="col-lg-7 col-12">
            <div class="custom-block bg-white">
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                    <li class="nav-item" role="presentation">
                        <button class="nav-link active" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile-tab-pane" type="button" role="tab" aria-controls="profile-tab-pane" aria-selected="true">Profile</button>
                    </li>
                    
                    <li class="nav-item" role="presentation">
                                        <button class="nav-link" id="password-tab" data-bs-toggle="tab" data-bs-target="#password-tab-pane" type="button" role="tab" aria-controls="password-tab-pane" aria-selected="false">Password</button>
                                    </li>

                                    <li class="nav-item" role="presentation">
                                        <button class="nav-link" id="notification-tab" data-bs-toggle="tab" data-bs-target="#notification-tab-pane" type="button" role="tab" aria-controls="notification-tab-pane" aria-selected="false">Notification</button>
                                    </li>
                                </ul>

                                <div class="tab-content" id="myTabContent">
                                    <div class="tab-pane fade show active" id="profile-tab-pane" role="tabpanel" aria-labelledby="profile-tab" tabindex="0">
                                        <h6 class="mb-4">User Profile</h6>

                                        <form class="custom-form profile-form" action="{% url 'settings:profile_update' %}" method="post" role="form" enctype="multipart/form-data">
                                            {% csrf_token %}
                                            <input class="form-control" type="text" name="profile-name" id="profile-name" placeholder="{{user.username}}">

                                            <input class="form-control" type="email" name="profile-email" id="profile-email" placeholder="{{user.email}}">

                                            <div class="input-group mb-1">
                                            {% if user.account.image %}
                                                <img src="{{user.account.image.url}}" class="profile-image img-fluid" alt="">
                                            {% else %}
                                                <img src="{% static "images/profile/empty.jpg" %}" class="profile-image img-fluid" alt="">
                                            {% endif %}
                                                <input type="file" class="form-control" id="inputGroupFile02" name="profile-image">
                                            </div>

                                            <div class="d-flex">
                                                <button type="button" class="form-control me-3">
                                                    Reset
                                                </button>

                                                <button type="submit" class="form-control ms-2">
                                                    Update
                                                </button>
                                            </div>
                                        </form>
                                    </div>

                                    <div class="tab-pane fade" id="password-tab-pane" role="tabpanel" aria-labelledby="password-tab" tabindex="0">
                                        <h6 class="mb-4">Password</h6>

                                        <form class="custom-form password-form" action="{% url 'settings:change_password' %}" method="post" role="form">
                                            {% csrf_token %}
                                            <input type="password" name="old_password" id="old_password" pattern="[0-9a-zA-Z]{4,10}" class="form-control" placeholder="Current Password" required="">

                                            <input type="password" name="new_password1" id="new_password1" pattern="[0-9a-zA-Z]{4,10}" class="form-control" placeholder="New Password" required="">

                                            <input type="password" name="new_password2" id="new_password2" pattern="[0-9a-zA-Z]{4,10}" class="form-control" placeholder="Confirm Password" required="">

                                            <div class="d-flex">
                                                <button type="button" class="form-control me-3">
                                                    Reset
                                                </button>

                                                <button type="submit" class="form-control ms-2">
                                                    Update Password
                                                </button>
                                            </div>
                                        </form>
                                    </div>

                                    <div class="tab-pane fade" id="notification-tab-pane" role="tabpanel" aria-labelledby="notification-tab" tabindex="0">
                                        <h6 class="mb-4">Notification</h6>

                                        <form class="custom-form notification-form" action="#" method="post" role="form">

                                            <div class="form-check form-switch d-flex mb-3 ps-0">
                                                <label class="form-check-label" for="flexSwitchCheckCheckedOne">Account activity</label>

                                                <input class="form-check-input ms-auto" type="checkbox" name="form-check-input" role="switch" id="flexSwitchCheckCheckedOne" checked>
                                            </div>

                                            <div class="form-check form-switch d-flex mb-3 ps-0">
                                                <label class="form-check-label" for="flexSwitchCheckCheckedTwo">Payment updated</label>

                                                <input class="form-check-input ms-auto" type="checkbox" name="form-check-input" role="switch" id="flexSwitchCheckCheckedTwo" checked>
                                            </div>

                                            <div class="d-flex mt-4">
                                                <button type="button" class="form-control me-3">
                                                    Reset
                                                </button>

                                                <button type="submit" class="form-control ms-2">
                                                    Update Password
                                                </button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-5 col-12">
                            <div class="custom-block custom-block-contact">
                                <h6 class="mb-4">Still can’t find what you looking for?</h6>

                                <p>
                                    <strong>Call us:</strong>
                                    <a href="tel: 305-240-9671" class="ms-2">
                                        (60) 
                                        305-240-9671
                                    </a>
                                </p>

                                <a href="#" class="btn custom-btn custom-btn-bg-white mt-3">
                                    Chat with us
                                </a>
                            </div>
                        </div>
                    </div>
{% endblock content %}
