frilance/FAQ/urls.py
from django.urls import path
from FAQ import views

app_name = "FAQ"
urlpatterns = [
    path('', views.FAQ, name = "FAQ")
]

frilance/frilance/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path ('settings/', include('settings.urls')),
    path ("profile/", include('user_profile.urls')),
    path("transactions/", include('transactions.urls')),
    path ("faq/", include("FAQ.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frilance/user_profile/urls.py
from django.urls import path
from user_profile import views

app_name = "profile"
urlpatterns = [
    path('', views.profile, name = 'profile')
]

frilance/user_profile/models.py
from datetime import timedelta
from email.policy import default
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField
import random
from django.db.models.signals import post_save
from django.dispatch import receiver

class Account(models.Model):
    user = models.OneToOneField(User,
                                on_delete=models.CASCADE)
    image = models.ImageField(upload_to="user_images", blank = True)

    phone_number = PhoneNumberField()

    birthday = models.DateField(auto_now=False,
                                auto_now_add=False)
    
    address = models.TextField(help_text = 'E.x.: 551 Swanston Street, Melbourne')

    def __str__(self):
        return self.user.username
    
class Card(models.Model):
    CARD_TYPES = (
        ('P', 'Personal'),
        ('C', 'Commercial'),
    )

    user = models.OneToOneField(User,
                                on_delete=models.CASCADE)
    
    
    
    card_number =  models.CharField(max_length=16,
                                    unique=True,
                                    blank = True,
                                    help_text = "THE FIELD IS FILLED IN AUTOMATICALLY. LEAVE IT EMPTY")

    card_type = models.CharField(max_length=1,
                                 choices=CARD_TYPES,
                                 default = "P")
    
    creation_date = models.DateTimeField(auto_now_add=True)

    expiration_date = models.DateTimeField(default = timezone.now()+timedelta(days=365*10))
    
    balance = models.DecimalField(max_digits=10,
                                  decimal_places=2,
                                  default = 100)





    def __str__(self):
        return f'{self.card_number} ({self.user.username})'
    
    def save(self, *args, **kwargs):
        if not self.card_number:
            while True:
                card_number = ''.join(str(random.randint(0, 9)) for _ in range(16))
                if not Card.objects.filter(card_number=card_number).exists():
                    self.card_number = card_number
                    break
        super().save(*args, **kwargs)

@receiver(post_save, sender=User)
def create_user_card(sender, instance, created, **kwargs):
    if created:
        Card.objects.create(user=instance)

frilance/user_profile/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def profile(request):
    return render(request, 'user_profile/profile.html')

# Create your views here.

frilance/user_profile/templates/user_profile/profile.html
{% extends "main/base/base.html" %}
{% load static %}
        {% block content %}
                <main class="main-wrapper col-md-9 ms-sm-auto py-4 col-lg-9 px-md-4 border-start">
                    <div class="title-group mb-3">
                        <h1 class="h2 mb-0">Profile</h1>
                    </div>

                    <div class="row my-4">
                        <div class="col-lg-7 col-12">
                            <div class="custom-block custom-block-profile">
                                <div class="row">
                                    <div class="col-lg-12 col-12 mb-3">
                                        <h6>General</h6>
                                    </div>

                                    <div class="col-lg-3 col-12 mb-4 mb-lg-0">
                                        <div class="custom-block-profile-image-wrap">
                                        {% if user.account.image %}
                                            <img src="{{user.account.image.url}}" class="custom-block-profile-image img-fluid" alt="">
                                        {% else %}
                                            <img src="{% static "images/profile/empty.jpg" %}" class="custom-block-profile-image img-fluid" alt="">
                                        {% endif %}
                                            <a href="setting.html" class="bi-pencil-square custom-block-edit-icon"></a>
                                        </div>
                                    </div>

                                    <div class="col-lg-9 col-12">
                                        <p class="d-flex flex-wrap mb-2">
                                            <strong>Name:</strong>

                                            <span>{{user.username}}</span>
                                        </p>

                                        <p class="d-flex flex-wrap mb-2">
                                            <strong>Email:</strong>
                                            
                                            <a href="#">
                                                {{user.email}}
                                            </a>
                                        </p>

                                        <p class="d-flex flex-wrap mb-2">
                                            <strong>Phone:</strong>

                                            <a href="#">
                                                {{user.account.phone_number}}
                                            </a>
                                        </p>

                                        <p class="d-flex flex-wrap mb-2">
                                            <strong>Birthday:</strong>

                                            <span>{{user.account.birthday}}</span>
                                        </p>

                                        <p class="d-flex flex-wrap">
                                            <strong>Address:</strong>

                                            <span>{{user.account.address}}</span>
                                        </p>
                                    </div>
                                </div>
                            </div>

                            <div class="custom-block custom-block-profile bg-white">
                                <h6 class="mb-4">Card Information</h6>

                                <p class="d-flex flex-wrap mb-2">
                                    <strong>card ID:</strong>

                                    <span>{{user.card.card_number}}</span>
                                </p>

                                <p class="d-flex flex-wrap mb-2">
                                    <strong>Type:</strong>

                                    <span>{{user.card.get_card_type_display}}</span>
                                </p>

                                <p class="d-flex flex-wrap mb-2">
                                    <strong>Created:</strong>

                                    <span>{{user.card.creation_date}}</span>
                                </p>

                                <p class="d-flex flex-wrap mb-2">
                                    <strong>Valid Date:</strong>

                                    <span>{{user.card.expiration_date}}</span>
                                </p>
                            </div>
                        </div>

                        <div class="col-lg-5 col-12">
                            <div class="custom-block custom-block-contact">
                                <h6 class="mb-4">Still can’t find what you looking for?</h6>

                                <p>
                                    <strong>Call us:</strong>
                                    <a href="tel: 305-240-9671" class="ms-2">
                                        (60) 
                                        305-240-9671
                                    </a>
                                </p>

                                <a href="#" class="btn custom-btn custom-btn-bg-white mt-3">
                                    Chat with us
                                </a>
                            </div>
                        </div>
                    </div>

                    <footer class="site-footer">
                        <div class="container">
                            <div class="row">
                                
                                <div class="col-lg-12 col-12">
                                    <p class="copyright-text">Copyright © Mini Finance 2048 
                                    - Design: <a rel="sponsored" href="https://www.tooplate.com" target="_blank">Tooplate</a></p>
                                </div>

                            </div>
                        </div>
                    </footer>
                </main>

            </div>
        </div>
    
    {% endblock content %}
