frilance/FAQ/urls.py
from django.urls import path
from FAQ import views

app_name = "FAQ"
urlpatterns = [
    path('', views.FAQ, name = "FAQ")
]

frilance/frilance/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path ('settings/', include('settings.urls')),
    path ("profile/", include('user_profile.urls')),
    path("transactions/", include('transactions.urls')),
    path ("faq/", include("FAQ.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frilance/main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.main, name = 'main'),
    path ('login/', views.login_views, name = 'login' ),
    path('logout/', views.logout_views, name = 'logout'),
    path('registration/', views.register_views, name = 'registration')
]

frilance/settings/urls.py
from django.urls import path
from settings import views

app_name = "settings"

urlpatterns = [
    path("", views.settings, name = 'settings'),
    path('settings/profile_update/', views.profile_update, name='profile_update'),
    path('settings/change_password/', views.change_password, name='change_password'),

]

frilance/transactions/urls.py
from django.urls import path
from transactions import views

app_name = 'wallet'
urlpatterns = [
    path('', views.wallet, name = 'wallet'),
    path ('info/', views.transation_detail, name = 'transation_detail'),
    path ('transfer/', views.transfer, name = 'transfer' )
]

frilance/user_profile/urls.py
from django.urls import path
from user_profile import views

app_name = "profile"
urlpatterns = [
    path('', views.profile, name = 'profile')
]

frilance/main/models.py
from django.db import models

# Create your models here.

frilance/main/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.utils.datastructures import MultiValueDictKeyError
from user_profile.models import Account


@login_required
def main(request):
    return render(request, "main/index.html")


def login_views(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('profile:profile')

    return render(request, 'registration/login.html')


def logout_views(request):
    logout (request)

    return redirect('main:login')

def register_views(request):
    if request.method == 'POST':
        try:
            username = request.POST['username']
            email = request.POST['email']
            phone_number = request.POST['phone_number']
            birthday = request.POST['birthday']
            address = request.POST['address']
            password1 = request.POST['password1']
            password2 = request.POST['password2']

            if password1 == password2:
                user = User.objects.create_user(username=username,
                                                      email=email,
                                                      password= password1)
                
                user.save()

                account = Account(user = user,
                                  phone_number=phone_number,
                                  birthday = birthday,
                                  address = address)
                account.save()
                login(request, user)
                print('Пользователь создан')
                return redirect('profile:profile')
            
            else:
                print('Пароли не совпадают')

        except MultiValueDictKeyError as e:
            print(f"Ошибка: {e}")

    else:
        return render(request, 'registration/registration.html',{})

frilance/main/templates/main/base/base.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <meta name="description" content="">
        <meta name="author" content="Tooplate">

        <title>Mini Finance Dashboard Template</title>

        <!-- CSS FILES -->      
        <link rel="preconnect" href="https://fonts.googleapis.com">
        
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

        <link href="https://fonts.googleapis.com/css2?family=Unbounded:wght@300;400;700&display=swap" rel="stylesheet">

        <link href="{% static "css/bootstrap.min.css" %} " rel="stylesheet">

        <link href="{% static "css/bootstrap-icons.css" %} " rel="stylesheet">

        <link href="{% static "css/apexcharts.css" %} " rel="stylesheet">

        <link href="{% static "css/tooplate-mini-finance.css" %} " rel="stylesheet">
<!--

Tooplate 2135 Mini Finance

https://www.tooplate.com/view/2135-mini-finance

Bootstrap 5 Dashboard Admin Template

-->

</head>
    
<body>
    <header class="navbar sticky-top flex-md-nowrap">
        <div class="col-md-3 col-lg-3 me-0 px-3 fs-6">
            <a class="navbar-brand" href="index.html">
                <i class="bi-box"></i>
                Mini Finance
            </a>
        </div>

        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <form class="custom-form header-form ms-lg-3 ms-md-3 me-lg-auto me-md-auto order-2 order-lg-0 order-md-0" action="#" method="get" role="form">
            <input class="form-control" name="search" type="text" placeholder="Search" aria-label="Search">
        </form>

        <div class="navbar-nav me-lg-2">
            <div class="nav-item text-nowrap d-flex align-items-center">
                <div class="dropdown ps-3">
                    <a class="nav-link dropdown-toggle text-center" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" id="navbarLightDropdownMenuLink">
                        <i class="bi-bell"></i>
                        <span class="position-absolute start-100 translate-middle p-1 bg-danger border border-light rounded-circle">
                            <span class="visually-hidden">New alerts</span>
                        </span>
                    </a>

                    <ul class="dropdown-menu dropdown-menu-lg-end notifications-block-wrap bg-white shadow" aria-labelledby="navbarLightDropdownMenuLink">
                        <small>Notifications</small>

                        <li class="notifications-block border-bottom pb-2 mb-2">
                            <a class="dropdown-item d-flex  align-items-center" href="#">
                                <div class="notifications-icon-wrap bg-success">
                                    <i class="notifications-icon bi-check-circle-fill"></i>
                                </div>

                                <div>
                                    <span>Your account has been created successfuly.</span>

                                    <p>12 days ago</p>
                                </div>
                            </a>
                        </li>

                        <li class="notifications-block border-bottom pb-2 mb-2">
                            <a class="dropdown-item d-flex align-items-center" href="#">
                                <div class="notifications-icon-wrap bg-info">
                                    <i class="notifications-icon bi-folder"></i>
                                </div>

                                <div>
                                    <span>Please check. We have sent a Daily report.</span>

                                    <p>10 days ago</p>
                                </div>
                            </a>
                        </li>

                        <li class="notifications-block">
                            <a class="dropdown-item d-flex align-items-center" href="#">
                                <div class="notifications-icon-wrap bg-danger">
                                    <i class="notifications-icon bi-question-circle"></i>
                                </div>

                                <div>
                                    <span>Account verification failed.</span>

                                    <p>1 hour ago</p>
                                </div>
                            </a>
                        </li>
                    </ul>
                </div>

                <div class="dropdown ps-1">
                    <a class="nav-link dropdown-toggle text-center" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="bi-three-dots-vertical"></i>
                    </a>

                </div>

                <div class="dropdown px-3">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    {% if user.account.image %}
                        <img src="{{user.account.image.url}} " class="profile-image img-fluid" alt="">
                    {% else %}
                        <img src="{% static "images/profile/empty.jpg" %} " class="profile-image img-fluid" alt="">
                    {% endif %}
                    </a>
                    <ul class="dropdown-menu bg-white shadow">
                        <li>
                            <div class="dropdown-menu-profile-thumb d-flex">
                            {% if user.account.image %}
                                <img src="{{user.account.image.url}} " class="profile-image img-fluid me-3" alt="">
                            {% else %}
                                <img src="{% static "images/profile/empty.jpg" %} " class="profile-image img-fluid me-3" alt="">
                            {% endif %}

                                <div class="d-flex flex-column">
                                    <small>{{user.username}}</small>
                                    <a href="#">{{user.email}}</a>
                                </div>
                            </div>
                        </li>

                        <li>
                            <a class="dropdown-item" href="profile.html">
                                <i class="bi-person me-2"></i>
                                Profile
                            </a>
                        </li>

                        <li>
                            <a class="dropdown-item" href="setting.html">
                                <i class="bi-gear me-2"></i>
                                Settings
                            </a>
                        </li>

                        <li>
                            <a class="dropdown-item" href="help-center.html">
                                <i class="bi-question-circle me-2"></i>
                                Help
                            </a>
                        </li>

                        <li class="border-top mt-3 pt-2 mx-4">
                            <a class="dropdown-item ms-0 me-0" href="{% url "main:logout" %}">
                                <i class="bi-box-arrow-left me-2"></i>
                                Logout
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </header>

    <div class="container-fluid">
        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-3 d-md-block sidebar collapse">
                <div class="position-sticky py-4 px-3 sidebar-sticky">
                    <ul class="nav flex-column h-100">
                        <li class="nav-item {% if request.resolver_match.url_name == '/' %}active{% endif %}">
                            <a class="nav-link" href="{% url "main:main" %}">
                                <i class="bi-house-fill me-2"></i>
                                Overview
                            </a>
                        </li>
                        
                        <li class="nav-item {% if request.resolver_match.url_name == 'wallet' %}active{% endif %}">
                            <a class="nav-link" href="{% url "wallet:wallet" %}">
                                <i class="bi-wallet me-2"></i>
                                My Wallet
                            </a>
                        </li>
                        
                        <li class="nav-item {% if request.resolver_match.url_name == 'profile' %}active{% endif %}">
                            <a class="nav-link" href="{% url "profile:profile" %}">
                                <i class="bi-person me-2"></i>
                                Profile
                            </a>
                        </li>
                        
                        <li class="nav-item {% if request.resolver_match.url_name == 'settings' %}active{% endif %}">
                            <a class="nav-link" href="{% url "settings:settings" %}">
                                <i class="bi-gear me-2"></i>
                                Settings
                            </a>
                        </li>
                        
                        <li class="nav-item {% if request.resolver_match.url_name == 'FAQ' %}active{% endif %}">
                            <a class="nav-link" href="{% url "FAQ:FAQ" %}">
                                <i class="bi-question-circle me-2"></i>
                                Help Center
                            </a>
                        </li>
                        
                        <li class="nav-item featured-box mt-lg-5 mt-4 mb-4">
                            <img src="{% static "images/credit-card.png" %} " class="img-fluid" alt="">
                            <a class="btn custom-btn" href="#">Upgrade</a>
                        </li>
                        
                        <li class="nav-item border-top mt-auto pt-2">
                            <a class="nav-link" href="{% url "main:logout" %}">
                                <i class="bi-box-arrow-left me-2"></i>
                                Logout
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
        {% block content %}

        {% endblock content %}
        <footer class="site-footer">
            <div class="container">
                <div class="row">
                    
                    <div class="col-lg-12 col-12">
                        <p class="copyright-text">Copyright © Mini Finance 2048 
                        - Design: <a rel="sponsored" href="https://www.tooplate.com" target="_blank">Tooplate</a></p>
                    </div>

                </div>
            </div>
        </footer>
    </main>

</div>
</div>

<script src="{% static "js/jquery.min.js" %} "></script>
<script src="{% static "js/bootstrap.bundle.min.js" %} "></script>
<script src="{% static "js/custom.js" %} "></script>
{% block js %}

{% endblock js %}
    </body>
</html>